name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Users currently have to manually refresh the map to see new offers...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this to work
      placeholder: |
        The map should automatically update when new offers appear nearby...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered?
      placeholder: |
        - Push notifications for new offers
        - A refresh button with visual indicator

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Must have
        - Should have
        - Nice to have
        - Future consideration
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      multiple: true
      options:
        - Map Experience
        - QR/Verification
        - Wallet/Rewards
        - User Onboarding
        - Reels/Content
        - Search/Discovery
        - Performance
        - Analytics
        - Admin/Dashboard
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Write a user story for this feature
      placeholder: |
        As a [type of user]
        I want [some goal]
        So that [some reason]

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be complete?
      placeholder: |
        - Map updates automatically every 30 seconds
        - Visual indicator shows when update occurs
        - User can disable auto-update in settings
        - Performance impact < 5% CPU usage

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add any mockups, diagrams, or examples (drag and drop images)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
